export const CATEGORIES_ACTION_TYPE = {
    SET_CATEGORIES:"category/SET_CATEGORIES",
    FETCH_CATEGORY_START:"category/FETCH_CATEGORY_START",
    FETCH_CATEGORY_SUCCESS:"category/FETCH_CATEGORY_SUCCESS",
    FETCH_CATEGORY_FAIL:"category/FETCH_CATEGORY_FAIL",
}